version: "3.8"

services:
  db:
    image: postgres:12.2-alpine
    container_name: comments_database
    ports:
      - "5432:5432"
    env_file: db.env
    networks:
      - fullstack
    volumes:
      - database_postgres:/var/lib/postgresql/data

  api:
    build: .
    container_name: comments_rest_api
    environment:
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
      DB_DB: "postgres"
      DB_HOST: "db"
      DB_TABLE: "postgres"
      DB_PORT: "5432"
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - fullstack
volumes:
  database_postgres:

networks:
  fullstack:
    driver: bridge